language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules
  yarn: true

# S: Build Lifecycle
install:
  - yarn

stages:
  - name: deploy

jobs:
  include:
    - stage: deploy
      script:
        - npm run build
      deploy:
        provider: npm
        email: ""
        api_key: "${NPM_TOKEN}"
        skip_cleanup: true
        on:
          branch: master
branches:
  only:
    - master
